# ================= PERFORMANCE =================
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+UseParallelGC -Dfile.encoding=UTF-8

org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Reduce file system watching overhead
org.gradle.vfs.watch=false

# ================= ANDROID =================
android.useAndroidX=true
android.enableJetifier=true

# ================= RN =================
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

newArchEnabled=true
hermesEnabled=true

# ================= BUILD SPEED =================
android.nonTransitiveRClass=true
android.enableR8.fullMode=false

# Skip PNG crunching
android.enablePngCrunchInReleaseBuilds=false

edgeToEdgeEnabled=false
